module.exports = {
"APP_ENVIRONMENT":   process.env.APP_ENVIRONMENT,
"APP_MODULE":        process.env.APP_MODULE,
"DB_PROTOCOL":       process.env.DB_PROTOCOL,
"DB_URL":            process.env.DB_URL,
"SESSION_MODULE":    process.env.SESSION_MODULE,
"PORT":              process.env.PORT,
"Username":          process.env.Username,
"UserPassword":      process.env.UserPassword,
"CLOUDANT_API_KEY":  process.env.CLOUDANT_API_KEY,
"CLOUDANT_PASSWORD": process.env.CLOUDANT_PASSWORD,
"CLOUDANT_PORT":     process.env.CLOUDANT_PORT,
"USER_DB":           process.env.USER_DB,
"DB":                process.env.DB,
"PI_DB":             process.env.PI_DB,
"SESSION_DB":        process.env.SESSION_DB,
"MAIL_API_KEY":      "key-2e1c148b591cdd5767904c9e482b34ce",
"MAIL_DOMAIN":       process.env.MAIL_DOMAIN,
"MAIL_ID":           process.env.MAIL_ID,
"IV":                process.env.IV,
"SECRET_KEY":        process.env.SECRET_KEY,
};
// module.exports = {
// 	"APP_ENVIRONMENT":   "FS",
// 	"APP_MODULE":        "nano",
// 	"DB_PROTOCOL":       "http",
// 	"DB_URL":            "localhost",
// 	"SESSION_MODULE":    "sessionstore",
// 	"PORT":              55554,
// 	"Username":          "nirmal",
// 	"UserPassword":      "nirmal",
// 	"CLOUDANT_API_KEY":  "nirmal",
// 	"CLOUDANT_PASSWORD": "nirmal",
// 	"CLOUDANT_PORT":     5984,
// 	"USER_DB":           "yhsqizvkmp",
// 	"DB":                "meluha_db5",
// 	"PI_DB":             "meluha_db5_pi",
// 	"SESSION_DB":        "sessions",
// 	"MAIL_API_KEY":      "key-2e1c148b591cdd5767904c9e482b34ce",
// 	"MAIL_DOMAIN":       "mg.sensoryhealthsystems.com",
// 	"MAIL_ID":           "Sensory Health Systems Admin <noreply@sensoryhealthsystems.com>",
// 	"IV":                "EK9Hd0Ahf5PJ8eS8",
// 	"SECRET_KEY":        "sterceSllAfOterceSehT"
// };